version: '3.2'
services:
  service:
    build: ./service
    restart: always
    ports:
     - "8123:8123"
    depends_on:
     - db
    environment:
     - DATABASE_HOST=db
  db:
    build: ./database
    restart: always
    volumes:
      - ./database/data/:/var/lib/mysql
